# WHAT IS PYTORCH?
### It’s a Python-based scientific computing package targeted at two sets of audiences:

1. A replacement for NumPy to use the power of GPUs
2. a deep learning research platform that provides maximum flexibility and speed

### Getting Started
#### Tensors
Tensors are simliar to Numpy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [31]:
import torch

In [32]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2756e-39, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])


### Construct a randomly initialized matrix:

In [33]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4146, 0.3127, 0.7590],
        [0.0675, 0.7447, 0.8692],
        [0.3379, 0.2803, 0.5362],
        [0.5493, 0.9557, 0.4577],
        [0.5495, 0.0770, 0.3293]])


#### Construct a matrix filled zeros and of dype long:

In [34]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


#### Construct a tensor directly from data:

In [35]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9023, -0.2828,  0.6842],
        [ 0.7647,  0.2774,  1.9008],
        [-0.5767, -0.5334,  0.3470],
        [-0.3108, -0.7941, -0.0996],
        [-0.2213, -0.2230, -0.4420]])


#### Get its size:

In [36]:
print(x.size())
print(x.shape)

torch.Size([2])
torch.Size([2])


## Operations

There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [38]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

tensor([[0.7015, 1.6451, 1.2079],
        [0.2238, 1.8398, 0.9681],
        [0.6798, 1.3152, 1.1253],
        [0.4769, 1.0068, 0.7812],
        [0.6854, 1.1277, 0.5025]])
tensor([[0.7015, 1.6451, 1.2079],
        [0.2238, 1.8398, 0.9681],
        [0.6798, 1.3152, 1.1253],
        [0.4769, 1.0068, 0.7812],
        [0.6854, 1.1277, 0.5025]])


Addition: in-place

Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [18]:
# adds x to y
y.add_(x)
print(y)
print(y[:, 1])

tensor([[-8.3541e-01,  4.0484e-01,  1.4647e+00],
        [ 1.9938e+00,  6.9748e-01,  4.4366e+00],
        [-9.1051e-01, -5.7394e-01,  1.1877e+00],
        [ 1.9769e-01, -1.2158e+00, -2.8082e-03],
        [ 6.7200e-02, -3.3840e-01,  5.0238e-02]])
tensor([ 0.4048,  0.6975, -0.5739, -1.2158, -0.3384])


#### Resizing

In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


## NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [27]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[ 3.  3.  3.  3.  3.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [39]:
torch.cuda.is_available()

False

### CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [30]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!